# FerrisDB Funding
# 
# FerrisDB is an educational project focused on learning distributed systems and Rust.
# Your sponsorship helps us dedicate more time to:
# - 📚 Creating educational content and tutorials
# - 🛠️ Improving documentation and examples
# - 🚀 Developing new features for learning
# - 💬 Supporting the community
# - 🎯 Maintaining the project long-term
#
# Other ways to support FerrisDB:
# - ⭐ Star the repository
# - 🍴 Fork and experiment with the code
# - 📝 Contribute code, tests, or documentation
# - 💬 Share knowledge in discussions
# - 📢 Write about your learning journey

# GitHub Sponsors - Support the maintainers directly
github: [nullcoder]  # Replace with your actual GitHub username

