name: 🐛 Bug Report
description: Report a bug in FerrisDB
title: "[Bug]: "
labels: ["type:bug", "status:ready"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us reproduce and fix the issue.
        
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Tell us what happened
    validations:
      required: true
      
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Start with...
        2. Run command...
        3. See error...
    validations:
      required: true
      
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Tell us what should happen
    validations:
      required: true
      
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Tell us what actually happened
    validations:
      required: true
      
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - WAL (Write-Ahead Log)
        - MemTable
        - SSTable  
        - Storage Engine
        - Client Library
        - Server
        - Other
    validations:
      required: true
      
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide the following information:
        - OS: [e.g. Ubuntu 22.04, macOS 14.0, Windows 11]
        - Rust version: [e.g. 1.75.0]
        - FerrisDB version/commit: [e.g. v0.1.0 or commit hash]
      placeholder: |
        - OS: 
        - Rust version: 
        - FerrisDB version: 
    validations:
      required: true
      
  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Please paste any relevant log output
      render: shell
      placeholder: Paste logs here (will be automatically formatted)
      
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true