# Site settings
title: FerrisDB
description: >-
  Educational distributed database in Rust - Learning LSM-trees, MVCC, 
  and distributed systems with Claude Code. Inspired by FoundationDB.
baseurl: ""
url: "https://ferrisdb.org"
github_username: ferrisdb
repository: ferrisdb/ferrisdb

# Open Graph / Social Media
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/ferrisdb_logo.svg

# Build settings
markdown: kramdown
highlighter: rouge
theme: just-the-docs
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-paginate

# Kramdown settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Just the Docs settings
logo: "/assets/images/ferrisdb_logo.svg"
# favicon_ico: "/assets/images/favicon.ico" # TODO: Add ICO favicon when available
color_scheme: ferrisdb

# Google Analytics
ga_tracking: G-JPW5LY247F
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings

# Enable heading anchors for better navigation
heading_anchors: true

# Search configuration
search_enabled: true
search:
  # Sections in each page to be searched
  heading_level: 2
  # Maximum amount of previews per search result
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: true
  # Keyboard shortcut to focus the search bar
  focus_shortcut_key: 'k'

# Enable copy button on code blocks
enable_copy_code_button: true

# Callout titles
callout_color_scheme: light

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# External links (using aux_links instead - see below)

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "FerrisDB Team"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Site data
author:
  name: FerrisDB Team
  email: noreply@ferrisdb.org

# Social links
social_links:
  github: ferrisdb/ferrisdb

# Custom variables
project:
  name: Building a Database, Learning in Public
  tagline: "FerrisDB: Where a CRUD developer and an AI collaborate to build a real database from scratch, documenting every lesson learned along the way."
  repo_url: https://github.com/ferrisdb/ferrisdb
  warning: "⚠️ This is an educational project - not for production use"
  
# Just the Docs navigation
aux_links:
  "GitHub":
    - "//github.com/ferrisdb/ferrisdb"

# Hide aux links on print
aux_links_new_tab: true

# Navigation structure
nav_enabled: true
nav_sort: case_sensitive # or case_insensitive

# Expand/collapse navigation sections
nav_fold: true

# Show table of contents for child pages on parent pages
nav_child_link: true

# Enable "Edit this page on GitHub" link
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/ferrisdb/ferrisdb"
gh_edit_branch: "main"
gh_edit_source: docs
gh_edit_view_mode: "edit"

# Just the Docs uses front matter for navigation structure
# Pages define their hierarchy using:
# - nav_order: numeric ordering
# - parent: parent page title
# - has_children: true/false
# - nav_exclude: true to hide from nav

# Blog settings
paginate: 5
paginate_path: "/blog/page:num/"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - _posts/human-blog-post-template.md
  - _posts/claude-blog-post-template.md
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata

