name: Deploy Docs to GitHub Pages

on:
  push:
    branches: ["main"]
    paths:
      - 'docs/**'
      - '.github/workflows/deploy-docs.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: docs/package-lock.json
          
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4
        
      - name: Install dependencies
        run: |
          cd docs
          npm ci
          echo "✅ Dependencies installed"
          
      - name: Build with Astro
        run: |
          cd docs
          # Build the Starlight site
          npm run build
          echo "✅ Starlight build succeeded"
        env:
          NODE_ENV: production
          
      - name: Verify build output
        run: |
          cd docs/dist
          # Check that index.html exists and is valid
          if [ ! -f "index.html" ]; then
            echo "ERROR: index.html not generated"
            exit 1
          fi
          # Check for common Astro/Starlight build artifacts
          if [ ! -d "_astro" ]; then
            echo "ERROR: Astro assets directory not found"
            exit 1
          fi
          # Basic HTML validation - ensure it's not empty
          if [ ! -s "index.html" ]; then
            echo "ERROR: index.html is empty"
            exit 1
          fi
          echo "✅ Build verification passed"
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4