name: Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  jekyll:
    name: Jekyll Site Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true
        working-directory: docs

    - name: Build Jekyll site
      run: |
        cd docs
        bundle install
        bundle exec jekyll build --strict_front_matter
      env:
        JEKYLL_ENV: production

    - name: Test HTML
      run: |
        cd docs
        bundle exec htmlproofer ./_site --disable-external

  markdown:
    name: Markdown Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Lint markdown files
      uses: DavidAnson/markdownlint-cli2-action@v14
      with:
        globs: |
          **/*.md
          !target/**
          !**/target/**

  spellcheck:
    name: Spell Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check spelling
      uses: crate-ci/typos@master
      with:
        files: |
          docs/
          *.md
          src/
          ferrisdb-*/src/